### ISSUE TITLE
[Feature Request]: Hide gitignored files

### ISSUE THREAD

**Issue by thegeorgeous** [sabof/project-explorer#28]

**Comment by sabof** [comment]
ATM there is `pe/omit-regex`, and you can advice/redefine `pe/file-interesting-p` for more complex scenarios. I have nothing against the feature, but I don't think I'm going to implement it in the foreseeable  future.

**Comment by xperian** [comment]
PE becomes extremely slow if there are too many files in the project. I did the dirty trick to omit ignored files.

**Comment by sabof** [comment]
If somebody where to write a function that would process `.gitignore` format, I would be quite happy to include it.

**Comment by mbme** [comment]
Probably it would be easier to run `git check-ignore **/*` in repository root dir and process it's output.
Also seems that this task is related to #31 .

**Comment by sabof** [comment]
Yes, that should work

**Comment by sabof** [comment]
I've pushed an implementation on `devel`. To try it set `pe/omit-gitignore` to non-nil.

**Comment by mbme** [comment]
Works for me as expected. Thanks!

**Comment by mbme** [comment]
one note: when I'm reindexing project there are a lot of noisy messages about ignored files, so maybe it's better to remove `message` call from `pe/file-interesting-p`

**Comment by sabof** [comment]
Fixed

**Comment by xperian** [comment]
Great job.

**Comment by sabof** [comment]
The changes have been pushed on master.
