### ISSUE TITLE
Open Automatically at Beginning

### ISSUE THREAD

**Issue by windweller** [sabof/project-explorer#29]
How to set up ~/.emacs so project-explorer can be opened automatically every time when I start Emacs? I tried `(setq project-explorer t)` and it didn't work.

**Comment by sabof** [comment]
```
(let ((default-directory "~/my-project/"))
  (project-explorer-open))
```

**Comment by windweller** [comment]
Thank you!!

**Comment by windweller** [comment]
Wait....can it detect current directory?

**Comment by sabof** [comment]
I'd think if you just write `(project-explorer-open)`, it will open the directory emacs was started in. But you'll have to be careful where you open emacs -- you probably don't want your entire harddrive cached.
