### ISSUE TITLE
No project-explorer-helm available? 

### ISSUE THREAD

**Issue by ReneFroger** [sabof/project-explorer#30]
Thanks for sharing this interesting plugin! 

However, I have a question. I have Helm installed on Emacs, which is working fine. 

After a crash in Project-explorer-helm (which was available first time), it's not available anymore? 
When I type `M-x project-explorer-open`, the command is listed. When I type `M-x project-explorer-helm`, there is no command available, still not when I press Enter after that. 

To be sure, I uninstalled Project-Explorer and installed it again. But unfortunately, it didn't helped. 

Any suggestions?

**Comment by sabof** [comment]
I seem to have neglected to make it auto-load. If you add `(require 'project-explorer)` somewhere in your config, all commands would become available.

**Comment by ReneFroger** [comment]
That was a fast response. It solved my problem. Thanks for that!
