### ISSUE TITLE
[Feature Request] Toggle PE's Display

### ISSUE THREAD

**Issue by madhat2r** [sabof/project-explorer#32]
It would be nice if there were a toggle function that would show/hide PE depending on it's visibility. This would improve workflow as you could use the same key-binding to open or close it.

This would be especially useful after you have selected a file in PE and it pops you over to the newly opened file's buffer leaving PE open. Now you have to switch back to PE just to close.

**Comment by sabof** [comment]
I've created `project-explorer-toggle`

**Comment by madhat2r** [comment]
Awesome Thanks!
