### ISSUE TITLE
project-explorer-helm doesn't do anything on Enter

### ISSUE THREAD

**Issue by katspaugh** [sabof/project-explorer#34]
When I run `project-explorer-helm`, a list of files appears and can be filtered, but I can't do anything useful with the selection. Tried pressing <kbd>Enter</kbd>, <kbd>Tab</kbd>, <kbd>C-j</kbd>, <kbd>C-i</kbd>–helm window is closed but nothing else happens. Tested without my `.emacs.d`.

**Comment by sabof** [comment]
Looks like an upstream change

**Comment by sabof** [comment]
Should be working now

**Comment by katspaugh** [comment]
I confirm it works now, thank you very much!
