### ISSUE TITLE
hl-line doesn't move with pe/goto-current-file-on-open

### ISSUE THREAD

**Issue by katspaugh** [sabof/project-explorer#40]
<img src="https://cloud.githubusercontent.com/assets/381895/8165711/4fa00a70-139b-11e5-9153-d9d3da5d93cb.png" width="165" />
Cursor moves, but hl-line stays. Is there a way to move the highlighted line with the cursor?

**Comment by sabof** [comment]
`hl-line-highlight` seems to be what you're looking for. I guess it doesn't run unless the buffer is active. If you make a pull request I'll review it.
